"""Add Channel model

Revision ID: b8e0715eeaba
Revises: 7caaf6dd0cce
Create Date: 2025-08-19 16:08:42.614195

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8e0715eeaba"
down_revision: Union[str, Sequence[str], None] = "7caaf6dd0cce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_created_at"), "channel", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_channel_name"), "channel", ["name"], unique=False)
    op.create_index(op.f("ix_channel_org_id"), "channel", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_channel_org_id"), table_name="channel")
    op.drop_index(op.f("ix_channel_name"), table_name="channel")
    op.drop_index(op.f("ix_channel_created_at"), table_name="channel")
    op.drop_table("channel")
    # ### end Alembic commands ###
