"""Add Message model for threads and replies

Revision ID: c858cce272e8
Revises: 1f8db712882f
Create Date: 2025-08-20 13:51:26.550243

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c858cce272e8"
down_revision: Union[str, Sequence[str], None] = "1f8db712882f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=True),
        sa.Column(
            "body", sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False
        ),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_channel_id"), "message", ["channel_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_created_at"), "message", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_message_thread_id"), "message", ["thread_id"], unique=False
    )
    op.create_index(op.f("ix_message_user_id"), "message", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_user_id"), table_name="message")
    op.drop_index(op.f("ix_message_thread_id"), table_name="message")
    op.drop_index(op.f("ix_message_created_at"), table_name="message")
    op.drop_index(op.f("ix_message_channel_id"), table_name="message")
    op.drop_table("message")
    # ### end Alembic commands ###
