"""Add authentication fields to user table

Revision ID: f7298981ad16
Revises: b61baab4c604
Create Date: 2025-08-19 15:14:25.072960

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f7298981ad16"
down_revision: Union[str, Sequence[str], None] = "b61baab4c604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
